######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 27 01:35:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG -= qt
OBJECTS_DIR = obj

# Input
HEADERS += TinyColor.hxx
SOURCES += main.cxx TinyColor.cxx
